--- #YAML:1.0
name:               Algorithm-Graphs-TransitiveClosure
version:            2009110901
abstract:           Calculate the transitive closure.
author:
    - Abigail <algorithm-graphs-transitiveclosure@abigail.be>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    strict:               0
    Test::More:           0
    warnings:             0
requires:
    Exporter:  0
    perl:      5.006
    strict:    0
    warnings:  0
resources:
    repository:  git://github.com/Abigail/algorithm--graphs--transitiveclosure.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:  []
test_requires:
    strict:      0
    Test::More:  0
    warnings:    0
